apiVersion: v1
kind: Service
metadata:
  name: kowl-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: kowl
    app.kubernetes.io/name: kowl
  ports:
    - name: http
      protocol: TCP
      port: 80  # Port used by Redis inside the pod
      targetPort: http
      nodePort: 30181