replicaCount: 1

image:
  registry: quay.io
  # Use "cloudhut/kowl-business" for the business version
  repository: cloudhut/kowl
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 64Mi

kowl:
  config:
    kafka:
      brokers:
        - kafka:29092