apiVersion: v1
kind: Namespace
metadata:
  name: c05

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-end
  name: front-end
  namespace: c05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  strategy: {}
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 5678
          protocol: TCP
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-end
  name: hello
  namespace: c05
spec:
  ports:
  - nodePort: 30622
    port: 5678
    protocol: TCP
    targetPort: 5678
  selector:
    app: front-end
  sessionAffinity: None
  type: NodePort