apiVersion: v1
kind: Namespace
metadata:
  name: c02

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: cpu-loader
  name: pod1
  namespace: c02
spec:
  containers:
  - image: nginx
    name: pod1
    resources:
      requests:
        cpu: 20m
        memory: 10Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: cpu-loader
  name: pod2
  namespace: c02
spec:
  containers:
  - image: nginx
    name: pod2
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: cpu-loader2
  name: pod3
  namespace: c02
spec:
  containers:
  - image: nginx
    name: pod3
    resources:
      requests:
        cpu: 50m
        memory: 10Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always