apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: elk
spec:
  version: 8.11.1
  elasticsearchRefs:
  - name: elk
  daemonSet:
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0 
  config:
    revision: 2
    agent:
      monitoring:
        enabled: true
        use_output: monitoring
        logs: true
        metrics: true
    inputs:
    - id: logfile-system-835850a7-3f6b-4ae9-8d02-a9a15767cf39
      name: system-1
      revision: 1
      type: logfile
      use_output: default
      meta:
        package:
          name: system
          version: 1.20.4
      data_stream:
        namespace: default
      streams:
      - id: logfile-system.auth
        data_stream:
          dataset: system.auth
          type: logs
        paths:
        - /var/log/auth.log*
        - /var/log/secure*
        exclude_files:
        - .gz$
        multiline:
          pattern: ^\s
          match: after
        processors:
        - add_locale: { }
        - add_fields:
            target: ''
            fields:
              ecs.version: 1.5.0
      - id: logfile-system.syslog
        data_stream:
          dataset: system.syslog
          type: logs
        paths:
        - /var/log/messages*
        - /var/log/syslog*
        exclude_files:
        - .gz$
        multiline:
          pattern: ^\s
          match: after
        processors:
        - add_locale: { }
        - add_fields:
            target: ''
            fields:
              ecs.version: 1.5.0
    - id: system/metrics-system-835850a7-3f6b-4ae9-8d02-a9a15767cf39
      name: system-1
      revision: 1
      type: system/metrics
      use_output: default
      meta:
        package:
          name: system
          version: 1.20.4
      data_stream:
        namespace: default
      streams:
      - id: system/metrics-system.cpu
        data_stream:
          dataset: system.cpu
          type: metrics
        metricsets:
        - cpu
        cpu.metrics:
        - percentages
        - normalized_percentages
        period: 100s
      - id: system/metrics-system.diskio
        data_stream:
          dataset: system.diskio
          type: metrics
        metricsets:
        - diskio
        diskio.include_devices: { }
        period: 100s
      - id: system/metrics-system.filesystem
        data_stream:
          dataset: system.filesystem
          type: metrics
        metricsets:
        - filesystem
        period: 1m
        processors:
        - drop_event.when.regexp:
            system.filesystem.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
      - id: system/metrics-system.fsstat
        data_stream:
          dataset: system.fsstat
          type: metrics
        metricsets:
        - fsstat
        period: 1m
        processors:
        - drop_event.when.regexp:
            system.fsstat.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
      - id: system/metrics-system.load
        data_stream:
          dataset: system.load
          type: metrics
        metricsets:
        - load
        period: 100s
      - id: system/metrics-system.memory
        data_stream:
          dataset: system.memory
          type: metrics
        metricsets:
        - memory
        period: 100s
      - id: system/metrics-system.network
        data_stream:
          dataset: system.network
          type: metrics
        metricsets:
        - network
        period: 100s
        network.interfaces: { }
      - id: system/metrics-system.process
        data_stream:
          dataset: system.process
          type: metrics
        metricsets:
        - process
        period: 100s
        process.include_top_n.by_cpu: 5
        process.include_top_n.by_memory: 5
        process.cmdline.cache.enabled: true
        process.cgroups.enabled: false
        process.include_cpu_ticks: false
        processes:
        - .*
      - id: system/metrics-system.process_summary
        data_stream:
          dataset: system.process_summary
          type: metrics
        metricsets:
        - process_summary
        period: 100s
      - id: system/metrics-system.socket_summary
        data_stream:
          dataset: system.socket_summary
          type: metrics
        metricsets:
        - socket_summary
        period: 100s
      - id: system/metrics-system.uptime
        data_stream:
          dataset: system.uptime
          type: metrics
        metricsets:
        - uptime
        period: 100s