apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.11.1
  count: 1
  elasticsearchRef:
    name: quickstart2
  # http:
  #   service:
  #     spec:
  #       type: NodePort
  #       ports:
  #         - protocol: TCP
  #           port: 5601 
  #           targetPort: 5601
  #           nodePort: 31601