apiVersion: v1
kind: Namespace
metadata:
  name: c06

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-end
  name: presentation
  namespace: c06
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end
  strategy: {}
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 5678
          protocol: TCP
        resources: {}

