apiVersion: v1
kind: Namespace
metadata:
  name: c09

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: c09
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}