apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: bitnami/redis:6.2.5
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: '1'
              memory: 1000Mi
          ports:
          - containerPort: 6379
          env:
          - name: REDIS_CONF
            value: |
              # Your other Redis configuration options
              requirepass ""
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: dev-tools
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379  # Port used by Redis inside the pod
      #targetPort: 6379  # Port used by the Redis pod
      nodePort: 30379