kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # extraMounts:
  # - hostPath: C:\WS\Labs\kind\files
  #   containerPath: /files
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
  extraPortMappings:
  - containerPort: 80
    hostPort: 10080
    protocol: TCP
  - containerPort: 443
    hostPort: 10443
    protocol: TCP

  - containerPort: 30379      # redis
    hostPort: 6379
    listenAddress: "127.0.0.1" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp, can be orverride to udp

  - containerPort: 31672      # rabbitmq
    hostPort: 15672
  - containerPort: 30672
    hostPort: 5672

  - containerPort: 30092     # kafka
    hostPort: 9092 
  - containerPort: 30081     # kafka internal schema-registry 
    hostPort: 8081 
  - containerPort: 30181     # internal kowl nodeport
    hostPort: 18081

  - containerPort: 31920     # elasticsearch
    hostPort: 9200
  - containerPort: 31601     # kibana
    hostPort: 5601

  - containerPort: 32000     # grafana
    hostPort: 3300
  - containerPort: 32080     # prometheus
    hostPort: 3280
  - containerPort: 30903     # alertmanager
    hostPort: 3290
- role: worker
- role: worker
networking:
  disableDefaultCNI: false
  podSubnet: "10.244.0.0/16"