apiVersion: v1
kind: Namespace
metadata:
  name: c13

---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
  namespace: c13
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/busybox
    args:
    - /bin/sh
    - -c
    - sleep 30;
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
