apiVersion: v1
kind: Namespace
metadata:
  name: c18

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-db
  namespace: c18
spec:
  podSelector:
    matchLabels:
      app: db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              db-access: "true"

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-front
  namespace: c18
spec:
  podSelector:
    matchLabels:
      app: front
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              front-access: "true"

---
apiVersion: v1
kind: Pod
metadata:
  name: c18-newpood
  namespace: c18
spec:
  containers:
  - name: nginx
    image: nginx
