apiVersion: v1
kind: Namespace
metadata:
  name: c13

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sidecar
  name: sidecar
  namespace: c13
spec:
  containers:
  - image: nginx
    name: sidecar
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always